### ISSUE TITLE
Encoding issues when installing from Github

### ISSUE THREAD

**Issue by samitakamaki** [psychbruce/ChineseNames#1]
I am trying to install the ChineseNames package from Github: devtools::install_github("psychbruce/ChineseNames")

I get the following encoding error:
```
* installing *source* package 'ChineseNames' ...
** using staged installation
** R
Error : (converted from warning) unable to re-encode 'ChineseNames.R' lines 371, 373, 393, 394, 396, 397, 399, 400, 401, 402, 404, 405, 406, 407, 408, 410
ERROR: unable to collate and parse R files for package 'ChineseNames'
* removing 'D:/Apps/R-4.0.2/library/ChineseNames'
Error: Failed to install 'ChineseNames' from GitHub:
  (converted from warning) installation of package ‘C:/Users/gaute/AppData/Local/Temp/RtmpGO9Izu/file36c4726265b3/ChineseNames_0.6.0.tar.gz’ had non-zero exit status
```

**Comment by maiht520** [comment]
I installed the same error:

Installing package into ‘C:/Users/ADMIN/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'ChineseNames' ...
** using staged installation
** R
Error : (converted from warning) unable to re-encode 'ChineseNames.R' lines 371, 373, 393, 394, 396, 397, 399, 400, 401, 402, 404, 405, 406, 407, 408, 410
ERROR: unable to collate and parse R files for package 'ChineseNames'
* removing 'C:/Users/ADMIN/Documents/R/win-library/4.0/ChineseNames'
Error: Failed to install 'ChineseNames' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMIN/AppData/Local/Temp/Rtmpm4kIjY/file25046fa976d0/ChineseNames_0.6.0.tar.gz’ had non-zero exit status

**Comment by psychbruce** [comment]
Hi there, now the `ChineseNames` package v1.0.0 has been published on CRAN (https://CRAN.R-project.org/package=ChineseNames) and thus you can install with `install.packages("ChineseNames")`. There is no more error in the process of installation.
